services:
  weather-backend:
    container_name: weather-backend
    hostname: weather-backend
    # image: aw19062024.azurecr.io/samples/weather-backend:latest
    image: weather-backend:latest
    build:
      context: ./weather-backend
    networks:
      - weather-network
  
  weather-frontend:
    container_name: weather-frontend
    hostname: weather-frontend
    # image: aw19062024.azurecr.io/samples/weather-frontend:latest
    image: weather-frontend:latest
    build:
      context: ./weather-frontend
    networks:
      - weather-network
  
  weather-nginx:
    container_name: weather-nginx
    hostname: weather-nginx
    # image: aw19062024.azurecr.io/samples/weather-nginx:latest
    image: weather-nginx:latest
    build:
      context: ./weather-nginx
    networks:
      - weather-network
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - weather-backend
      - weather-frontend

networks:
  weather-network:
